// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI3LuMH96kLsAxi_Mip4S_65eD-Pk0Aig',
    appId: '1:1090257390663:web:2986957597ea4305957562',
    messagingSenderId: '1090257390663',
    projectId: 'collab-app-ca3fa',
    authDomain: 'collab-app-ca3fa.firebaseapp.com',
    storageBucket: 'collab-app-ca3fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV7Di_B7oa3ErlxIyMcg-wm0-4oEiWaYw',
    appId: '1:1090257390663:android:9c712ea4905dff3e957562',
    messagingSenderId: '1090257390663',
    projectId: 'collab-app-ca3fa',
    storageBucket: 'collab-app-ca3fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiKFHxiXE94s_oK7sTEdzLZwH7kT2LUww',
    appId: '1:1090257390663:ios:b7b9500e4021bfac957562',
    messagingSenderId: '1090257390663',
    projectId: 'collab-app-ca3fa',
    storageBucket: 'collab-app-ca3fa.firebasestorage.app',
    iosBundleId: 'com.example.collabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiKFHxiXE94s_oK7sTEdzLZwH7kT2LUww',
    appId: '1:1090257390663:ios:b7b9500e4021bfac957562',
    messagingSenderId: '1090257390663',
    projectId: 'collab-app-ca3fa',
    storageBucket: 'collab-app-ca3fa.firebasestorage.app',
    iosBundleId: 'com.example.collabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI3LuMH96kLsAxi_Mip4S_65eD-Pk0Aig',
    appId: '1:1090257390663:web:205fd66fc8972345957562',
    messagingSenderId: '1090257390663',
    projectId: 'collab-app-ca3fa',
    authDomain: 'collab-app-ca3fa.firebaseapp.com',
    storageBucket: 'collab-app-ca3fa.firebasestorage.app',
  );
}
